name: "Test Form"
description: "Minimal issue form to verify"
title: "Compatibility report"
body:
  - type: input
    id: brand
    attributes:
      label: Brand
      placeholder: Airton
    validations:
      required: true
