# .github/workflows/autoclose-compatibility.yml
name: Auto-close Compatibility Reports

on:
  issues:
    types: [opened, labeled]

permissions:
  contents: read
  issues: write

jobs:
  close_compat:
    if: >
      (github.event.action == 'labeled' && github.event.label.name == 'compatibility')
      || (github.event.action == 'opened' && contains(toJson(github.event.issue.labels), '"compatibility"'))
    runs-on: ubuntu-latest
    steps:
      - name: Close compatibility issues automatically
        uses: peter-evans/close-issue@v3
        with:
          comment: |
            🔒 Thanks for submitting a compatibility report!
            This issue is closed automatically to keep the tracker clean.
            Your report remains visible and will be aggregated into COMPATIBILITY.md.
