name: ESPHome Auto-Build (Latest Version)

on:
  schedule:
    - cron: '0 8 * * 6'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install latest ESPHome
        run: pip install --upgrade esphome

      - name: Compile firmware
        run: esphome compile esphome-acw02-error.yaml
