name: Manual Release with Auto Date Tag

on:
  workflow_dispatch:

jobs:
  manual-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compute base tag name (YYYY.M.D)
        id: base
        run: |
          BASE_TAG=$(date +'%Y.%-m.%-d')
          echo "base_tag=$BASE_TAG" >> $GITHUB_OUTPUT

      - name: Find available tag (base or -1/-2/etc.)
        id: tag
        run: |
          git fetch --tags
          BASE="${{ steps.base.outputs.base_tag }}"
          TAG="$BASE"
          i=1
          while git rev-parse "refs/tags/$TAG" >/dev/null 2>&1; do
            TAG="${BASE}-${i}"
            i=$((i+1))
          done
          echo "tag_name=$TAG" >> $GITHUB_OUTPUT
          echo "Using tag: $TAG"

      - name: Create git tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.tag.outputs.tag_name }}
          git push origin ${{ steps.tag.outputs.tag_name }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag_name }}
          name: Release ${{ steps.tag.outputs.tag_name }}
          files: acw02_esphome_${{ steps.tag.outputs.tag_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
