name: Manual Release with Date Tag

on:
  workflow_dispatch:

jobs:
  manual-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # autorise à créer tag et release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compute date tag
        id: date
        run: |
          DATE_TAG=$(date +'%Y.%-m.%-d')
          echo "date_tag=$DATE_TAG" >> $GITHUB_OUTPUT

      - name: Check if tag already exists
        id: check
        run: |
          TAG_EXISTS=$(git ls-remote --tags origin | grep -c "refs/tags/${{ steps.date.outputs.date_tag }}")
          echo "exists=$TAG_EXISTS" >> $GITHUB_OUTPUT

      - name: Create git tag
        if: steps.check.outputs.exists == '0'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.date.outputs.date_tag }}
          git push origin ${{ steps.date.outputs.date_tag }}

      - name: Prepare ZIP archive
        run: |
          mkdir release
          cp acw02.yaml release/
          cp README.md release/ || true
          cp -r custom_components release/
          cd release
          zip -r ../acw02_esphome_${{ steps.date.outputs.date_tag }}.zip .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.date.outputs.date_tag }}
          name: Release ${{ steps.date.outputs.date_tag }}
          files: acw02_esphome_${{ steps.date.outputs.date_tag }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
