name: Manual Release with Auto Tag and Changelog

on:
  workflow_dispatch:

jobs:
  manual-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # nécessaire pour créer tag et release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compute base tag name (YYYY.M.D)
        id: base
        run: |
          BASE_TAG=$(date +'%Y.%-m.%-d')
          echo "base_tag=$BASE_TAG" >> $GITHUB_OUTPUT

      - name: Find available tag (base or -1/-2/etc.)
        id: tag
        run: |
          git fetch --tags
          BASE="${{ steps.base.outputs.base_tag }}"
          TAG="$BASE"
          i=1
          while git rev-parse "refs/tags/$TAG" >/dev/null 2>&1; do
            TAG="${BASE}-${i}"
            i=$((i+1))
          done
          echo "tag_name=$TAG" >> $GITHUB_OUTPUT
          echo "Using tag: $TAG"

      - name: Read ESPHome version from docker/.env
        id: esphome
        run: |
          VERSION=$(grep '^ESPHOME_VERSION=' docker/.env | sed 's/ESPHOME_VERSION[[:space:]]*=[[:space:]]*//')
          echo "esphome_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Generate changelog since last tag
        id: changelog
        run: |
          git fetch --tags
          LAST_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          {
            echo "### ESPHome version: ${{ steps.esphome.outputs.esphome_version }}"
            echo ""
            if [ -n "$LAST_TAG" ]; then
              echo "Changes since $LAST_TAG:"
              git log "$LAST_TAG"..HEAD --pretty=format:"- %s (%h)"
            else
              echo "Initial release"
            fi
          } > changelog.txt

      - name: Create git tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.tag.outputs.tag_name }}
          git push origin ${{ steps.tag.outputs.tag_name }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag_name }}
          name: Release ${{ steps.tag.outputs.tag_name }}
          files: acw02_esphome_${{ steps.tag.outputs.tag_name }}.zip
          body_path: changelog.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
